services:
  proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DOCKER_DATA-../data}/proxy/data:/data
      - ${DOCKER_DATA-../data}/proxy/letsencrypt:/etc/letsencrypt
